camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.1
  num_images: 100
chroma_key_settings: {}
class_names:
- whitething
debug:
  backgrounds: data/backgrounds
  bboxes: data/debug/bboxes
  coloringmask: data/debug/coloringmask
  coloringmask_random_bg: data/debug/coloringmask_random_bg
  combined_mask: data/debug/combined_mask
  contours: data/debug/contours
  depthmask: data/debug/depthmask
  maskinyolo: data/debug/maskinyolo
  placement: data/debug/placement
  rgbmask: data/debug/rgbmask
depth_thresholds: {}
image_counters: {}
output:
  background_image_dir: data/backgrounds
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
  test_image_dir: data/images/test
  test_label_dir: data/labels/test
  train_image_dir: data/images/train
  train_label_dir: data/labels/train
  val_image_dir: data/images/val
  val_label_dir: data/labels/val
rois: {}
