camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.36
  num_images: 50
chroma_key:
  lower_color:
  - 0
  - 0
  - 89
  upper_color:
  - 179
  - 255
  - 255
class_names:
- whitething
- testthing
- blackthing
debug:
  bboxes: data/debug/bboxes
  combined_mask: data/debug/combined_mask
  contours: data/debug/contours
  depthmask: data/debug/depthmask
  rgbmask: data/debug/rgbmask
depth_thresholds:
  blackthing:
    max: 631
    min: 500
  testthing:
    max: 647
    min: 588
  whitething:
    max: 586
    min: 500
image_counters:
  blackthing: 51
  testthing: 51
  whitething: 51
output:
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
  train_image_dir: data/images/train
  train_label_dir: data/labels/train
  val_image_dir: data/images/val
  val_label_dir: data/labels/val
rois:
- height: 224
  width: 215
  x: 490
  y: 89
