camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.01
  num_images: 100
chroma_key:
  lower_color:
  - 0
  - 80
  - 0
  upper_color:
  - 179
  - 255
  - 255
class_names:
- whitething
debug:
  bboxes: data/debug/bboxes
  coloringmask: data/debug/coloringmask
  coloringmask_random_bg: data/debug/coloringmask_random_bg
  combined_mask: data/debug/combined_mask
  contours: data/debug/contours
  depthmask: data/debug/depthmask
  maskinyolo: data/debug/maskinyolo
  rgbmask: data/debug/rgbmask
depth_thresholds:
  whitething:
    max: 827
    min: 500
image_counters:
  whitething: 101
output:
  background_image_dir: data/backgrounds
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
  train_image_dir: data/images/train
  train_label_dir: data/labels/train
  val_image_dir: data/images/val
  val_label_dir: data/labels/val
rois:
- height: 177
  width: 208
  x: 616
  y: 73
