camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.25
  num_images: 50
chroma_key:
  lower_color:
  - 0
  - 0
  - 0
  upper_color:
  - 179
  - 255
  - 149
class_names: []
debug:
  bboxes: data/debug/bboxes
  combined_mask: data/debug/combined_mask
  contours: data/debug/contours
  depthmask: data/debug/depthmask
  rgbmask: data/debug/rgbmask
depth_thresholds: {}
image_counters: {}
output:
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
  train_image_dir: data/images/train
  train_label_dir: data/labels/train
  val_image_dir: data/images/val
  val_label_dir: data/labels/val
rois:
- height: 113
  width: 108
  x: 655
  y: 155
