camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.25
  num_images: 50
chroma_key:
  lower_color:
  - 0
  - 80
  - 0
  upper_color:
  - 179
  - 255
  - 255
class_names:
- whitething
- testthing
- blackthing
- smallthing
debug:
  bboxes: data/debug/bboxes
  combined_mask: data/debug/combined_mask
  contours: data/debug/contours
  depthmask: data/debug/depthmask
  rgbmask: data/debug/rgbmask
depth_thresholds:
  blackthing:
    max: 617
    min: 500
  smallthing:
    max: 606
    min: 500
  testthing:
    max: 633
    min: 500
  whitething:
    max: 594
    min: 500
image_counters:
  blackthing: 51
  smallthing: 51
  testthing: 51
  whitething: 51
output:
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
  train_image_dir: data/images/train
  train_label_dir: data/labels/train
  val_image_dir: data/images/val
  val_label_dir: data/labels/val
rois:
- height: 190
  width: 190
  x: 572
  y: 132
