augmentation:
  enabled: true
  transformations:
  - p: 0.5
    type: HorizontalFlip
  - p: 0.5
    rotate_limit: 15
    scale_limit: 0.1
    shift_limit: 0.0625
    type: ShiftScaleRotate
  - brightness_limit:
    - 0.1
    - 0.3
    contrast_limit:
    - 0.1
    - 0.3
    p: 0.5
    type: RandomBrightnessContrast
  - hue_shift_limit: 20
    p: 0.5
    sat_shift_limit: 30
    type: HueSaturationValue
    val_shift_limit: 20
  - height: 640
    p: 0.5
    type: RandomCrop
    width: 640
  - height: 640
    p: 1.0
    type: Resize
    width: 640
camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.25
  num_images: 50
chroma_key:
  lower_color:
  - 0
  - 0
  - 0
  upper_color:
  - 168
  - 166
  - 200
class_names: []
depth_thresholds: {}
image_counters: {}
output:
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
  train_image_dir: data/images/train
  train_label_dir: data/labels/train
  val_image_dir: data/images/val
  val_label_dir: data/labels/val
rois:
- height: 179
  width: 178
  x: 830
  y: 50
