camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.25
  num_images: 50
chroma_key:
  lower_color:
  - 0
  - 58
  - 0
  upper_color:
  - 179
  - 255
  - 255
class_name: object
depth_threshold:
  max: 585
  min: 561
output:
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
rois:
- height: 251
  width: 290
  x: 565
  y: 134
