camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.25
  num_images: 50
chroma_key:
  lower_color:
  - 0
  - 0
  - 0
  upper_color:
  - 179
  - 73
  - 1
class_name: object
depth_threshold:
  max: 584
  min: 557
output:
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
rois:
- height: 231
  width: 244
  x: 567
  y: 156
