camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.1
  num_images: 152
chroma_key_settings:
  blackthing:
    0:
      lower_color:
      - 24
      - 0
      - 73
      upper_color:
      - 179
      - 255
      - 255
    1:
      lower_color:
      - 0
      - 0
      - 72
      upper_color:
      - 179
      - 255
      - 255
    2:
      lower_color:
      - 0
      - 0
      - 51
      upper_color:
      - 179
      - 255
      - 255
    3:
      lower_color:
      - 0
      - 0
      - 47
      upper_color:
      - 179
      - 255
      - 255
  fanthing:
    0:
      lower_color:
      - 30
      - 73
      - 65
      upper_color:
      - 179
      - 255
      - 255
    1:
      lower_color:
      - 35
      - 114
      - 68
      upper_color:
      - 179
      - 255
      - 255
    2:
      lower_color:
      - 0
      - 72
      - 75
      upper_color:
      - 179
      - 255
      - 255
    3:
      lower_color:
      - 36
      - 66
      - 47
      upper_color:
      - 179
      - 255
      - 255
  orangething:
    0:
      lower_color:
      - 31
      - 0
      - 0
      upper_color:
      - 179
      - 255
      - 255
    1:
      lower_color:
      - 45
      - 0
      - 0
      upper_color:
      - 179
      - 255
      - 255
    2:
      lower_color:
      - 54
      - 0
      - 0
      upper_color:
      - 179
      - 255
      - 255
    3:
      lower_color:
      - 56
      - 0
      - 0
      upper_color:
      - 179
      - 255
      - 255
  smallthing:
    0:
      lower_color:
      - 0
      - 120
      - 93
      upper_color:
      - 179
      - 255
      - 255
    1:
      lower_color:
      - 0
      - 101
      - 82
      upper_color:
      - 179
      - 255
      - 255
    2:
      lower_color:
      - 0
      - 106
      - 105
      upper_color:
      - 179
      - 255
      - 255
    3:
      lower_color:
      - 0
      - 231
      - 0
      upper_color:
      - 179
      - 255
      - 255
  yellowthing:
    0:
      lower_color:
      - 46
      - 0
      - 0
      upper_color:
      - 179
      - 255
      - 255
    1:
      lower_color:
      - 45
      - 0
      - 0
      upper_color:
      - 179
      - 255
      - 255
    2:
      lower_color:
      - 55
      - 0
      - 0
      upper_color:
      - 179
      - 255
      - 255
    3:
      lower_color:
      - 66
      - 0
      - 0
      upper_color:
      - 179
      - 255
      - 255
class_names:
- blackthing
- yellowthing
- smallthing
- orangething
- fanthing
debug:
  backgrounds: data/backgrounds
  bboxes: data/debug/bboxes
  coloringmask: data/debug/coloringmask
  coloringmask_random_bg: data/debug/coloringmask_random_bg
  combined_mask: data/debug/combined_mask
  contours: data/debug/contours
  depthmask: data/debug/depthmask
  maskinyolo: data/debug/maskinyolo
  rgbmask: data/debug/rgbmask
depth_thresholds:
  blackthing:
    0:
      max: 646
      min: 500
    1:
      max: 633
      min: 500
    2:
      max: 596
      min: 500
    3:
      max: 677
      min: 500
  fanthing:
    0:
      max: 631
      min: 500
    1:
      max: 630
      min: 500
    2:
      max: 637
      min: 500
    3:
      max: 603
      min: 500
  orangething:
    0:
      max: 632
      min: 500
    1:
      max: 644
      min: 500
    2:
      max: 635
      min: 500
    3:
      max: 630
      min: 500
  smallthing:
    0:
      max: 636
      min: 500
    1:
      max: 647
      min: 500
    2:
      max: 679
      min: 500
    3:
      max: 652
      min: 500
  yellowthing:
    0:
      max: 652
      min: 500
    1:
      max: 651
      min: 500
    2:
      max: 671
      min: 500
    3:
      max: 592
      min: 500
image_counters:
  blackthing:
    0: 39
    1: 39
    2: 39
    3: 39
  fanthing:
    0: 39
    1: 39
    2: 39
  orangething:
    0: 39
    1: 39
    2: 39
    3: 39
  smallthing:
    0: 39
    1: 39
    2: 39
    3: 39
  yellowthing:
    0: 39
    1: 39
    2: 39
    3: 39
output:
  background_image_dir: data/backgrounds
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
  test_image_dir: data/images/test
  test_label_dir: data/labels/test
  train_image_dir: data/images/train
  train_label_dir: data/labels/train
  val_image_dir: data/images/val
  val_label_dir: data/labels/val
rois:
  blackthing:
    0:
    - height: 205
      width: 215
      x: 552
      y: 126
    1:
    - height: 208
      width: 223
      x: 553
      y: 123
    2:
    - height: 233
      width: 251
      x: 37
      y: 68
    3:
    - height: 208
      width: 192
      x: 1048
      y: 74
  fanthing:
    0:
    - height: 171
      width: 178
      x: 471
      y: 110
    1:
    - height: 213
      width: 213
      x: 452
      y: 99
    2:
    - height: 212
      width: 220
      x: 448
      y: 99
    3:
    - height: 247
      width: 267
      x: 421
      y: 70
  orangething:
    0:
    - height: 140
      width: 144
      x: 493
      y: 129
    1:
    - height: 223
      width: 218
      x: 449
      y: 91
    2:
    - height: 223
      width: 236
      x: 442
      y: 90
    3:
    - height: 230
      width: 247
      x: 435
      y: 76
  smallthing:
    0:
    - height: 217
      width: 255
      x: 467
      y: 103
    1:
    - height: 171
      width: 189
      x: 498
      y: 120
    2:
    - height: 154
      width: 152
      x: 1011
      y: 110
    3:
    - height: 135
      width: 166
      x: 482
      y: 140
  yellowthing:
    0:
    - height: 147
      width: 150
      x: 606
      y: 164
    1:
    - height: 224
      width: 240
      x: 562
      y: 102
    2:
    - height: 251
      width: 244
      x: 993
      y: 88
    3:
    - height: 264
      width: 268
      x: 14
      y: 55
