camera:
  fps: 30
  resolution:
  - 1280
  - 720
capture:
  interval: 0.15
  num_images: 50
chroma_key:
  lower_color:
  - 62
  - 212
  - 0
  upper_color:
  - 179
  - 255
  - 255
class_names:
- smallthing
- blackthing
- testthing
- yellowthing
debug:
  bboxes: data/debug/bboxes
  coloringmask: data/debug/coloringmask
  coloringmask_random_bg: data/debug/coloringmask_random_bg
  combined_mask: data/debug/combined_mask
  contours: data/debug/contours
  depthmask: data/debug/depthmask
  maskinyolo: data/debug/maskinyolo
  rgbmask: data/debug/rgbmask
depth_thresholds:
  blackthing:
    max: 673
    min: 500
  smallthing:
    max: 673
    min: 500
  testthing:
    max: 682
    min: 500
  yellowthing:
    max: 684
    min: 500
image_counters:
  blackthing: 51
  smallthing: 51
  testthing: 51
  yellowthing: 51
output:
  background_image_dir: data/backgrounds
  depth_dir: data/depth_maps
  image_dir: data/images
  label_dir: data/labels
  train_image_dir: data/images/train
  train_label_dir: data/labels/train
  val_image_dir: data/images/val
  val_label_dir: data/labels/val
rois:
- height: 161
  width: 176
  x: 616
  y: 126
